language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libsdl-image1.2-dev
            - libsdl-dev
            - libsdl-net1.2
            - libsdl-net1.2-dev
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - os: osx
      osx_image: xcode10
      addons:
        homebrew:
          packages:
            - gcc@7
            - sdl
            - sdl_net
            - sdl_image
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - mkdir build && cd build
  - cmake ..
  - make
